//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleWCFKlijent.MagacinServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KategorijaCon", Namespace="http://schemas.datacontract.org/2004/07/WebWCFServisHost.Models")]
    [System.SerializableAttribute()]
    public partial class KategorijaCon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KategorijaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivKategorijeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OpisKategorijeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KategorijaId {
            get {
                return this.KategorijaIdField;
            }
            set {
                if ((this.KategorijaIdField.Equals(value) != true)) {
                    this.KategorijaIdField = value;
                    this.RaisePropertyChanged("KategorijaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivKategorije {
            get {
                return this.NazivKategorijeField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivKategorijeField, value) != true)) {
                    this.NazivKategorijeField = value;
                    this.RaisePropertyChanged("NazivKategorije");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpisKategorije {
            get {
                return this.OpisKategorijeField;
            }
            set {
                if ((object.ReferenceEquals(this.OpisKategorijeField, value) != true)) {
                    this.OpisKategorijeField = value;
                    this.RaisePropertyChanged("OpisKategorije");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProizvodCon", Namespace="http://schemas.datacontract.org/2004/07/WebWCFServisHost.Models")]
    [System.SerializableAttribute()]
    public partial class ProizvodCon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CijenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KategorijaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int KolicinaNaLageruField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivProizvodaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProizvodIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cijena {
            get {
                return this.CijenaField;
            }
            set {
                if ((this.CijenaField.Equals(value) != true)) {
                    this.CijenaField = value;
                    this.RaisePropertyChanged("Cijena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KategorijaId {
            get {
                return this.KategorijaIdField;
            }
            set {
                if ((this.KategorijaIdField.Equals(value) != true)) {
                    this.KategorijaIdField = value;
                    this.RaisePropertyChanged("KategorijaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int KolicinaNaLageru {
            get {
                return this.KolicinaNaLageruField;
            }
            set {
                if ((this.KolicinaNaLageruField.Equals(value) != true)) {
                    this.KolicinaNaLageruField = value;
                    this.RaisePropertyChanged("KolicinaNaLageru");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivProizvoda {
            get {
                return this.NazivProizvodaField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivProizvodaField, value) != true)) {
                    this.NazivProizvodaField = value;
                    this.RaisePropertyChanged("NazivProizvoda");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProizvodId {
            get {
                return this.ProizvodIdField;
            }
            set {
                if ((this.ProizvodIdField.Equals(value) != true)) {
                    this.ProizvodIdField = value;
                    this.RaisePropertyChanged("ProizvodId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MagacinServiceReference.IMagacinService")]
    public interface IMagacinService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagacinService/VratiKategorije", ReplyAction="http://tempuri.org/IMagacinService/VratiKategorijeResponse")]
        ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon[] VratiKategorije();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagacinService/VratiKategorije", ReplyAction="http://tempuri.org/IMagacinService/VratiKategorijeResponse")]
        System.Threading.Tasks.Task<ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon[]> VratiKategorijeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagacinService/VratiKategoriju", ReplyAction="http://tempuri.org/IMagacinService/VratiKategorijuResponse")]
        ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon VratiKategoriju(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagacinService/VratiKategoriju", ReplyAction="http://tempuri.org/IMagacinService/VratiKategorijuResponse")]
        System.Threading.Tasks.Task<ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon> VratiKategorijuAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagacinService/VratiProizvode", ReplyAction="http://tempuri.org/IMagacinService/VratiProizvodeResponse")]
        ConsoleWCFKlijent.MagacinServiceReference.ProizvodCon[] VratiProizvode(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMagacinService/VratiProizvode", ReplyAction="http://tempuri.org/IMagacinService/VratiProizvodeResponse")]
        System.Threading.Tasks.Task<ConsoleWCFKlijent.MagacinServiceReference.ProizvodCon[]> VratiProizvodeAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMagacinServiceChannel : ConsoleWCFKlijent.MagacinServiceReference.IMagacinService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MagacinServiceClient : System.ServiceModel.ClientBase<ConsoleWCFKlijent.MagacinServiceReference.IMagacinService>, ConsoleWCFKlijent.MagacinServiceReference.IMagacinService {
        
        public MagacinServiceClient() {
        }
        
        public MagacinServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MagacinServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagacinServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MagacinServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon[] VratiKategorije() {
            return base.Channel.VratiKategorije();
        }
        
        public System.Threading.Tasks.Task<ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon[]> VratiKategorijeAsync() {
            return base.Channel.VratiKategorijeAsync();
        }
        
        public ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon VratiKategoriju(int id) {
            return base.Channel.VratiKategoriju(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleWCFKlijent.MagacinServiceReference.KategorijaCon> VratiKategorijuAsync(int id) {
            return base.Channel.VratiKategorijuAsync(id);
        }
        
        public ConsoleWCFKlijent.MagacinServiceReference.ProizvodCon[] VratiProizvode(int id) {
            return base.Channel.VratiProizvode(id);
        }
        
        public System.Threading.Tasks.Task<ConsoleWCFKlijent.MagacinServiceReference.ProizvodCon[]> VratiProizvodeAsync(int id) {
            return base.Channel.VratiProizvodeAsync(id);
        }
    }
}
